name: build

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.45.2/ktlint && chmod a+x ktlint

      - name: Run ktlint
        run: ./ktlint --relative src/**/*.kt

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
